version: '3.8'

services:
  api:
    build: ./backend
    container_name: eticaret-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  tracker:
    build: ./backend
    container_name: eticaret-tracker
    command: python tracker.py
    volumes:
      - ./backend:/app
    depends_on:
      - api
    restart: always

